"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do
not exceed four million,find the sum of the even-valued terms.

Sample Input 1:
100
Sample Output 1:
44
"""
n = int(input())
F_0 = 0
F_1 = 1
sum_fib = 0
while F_1 <= n:
    if F_1 % 2 == 0:
        sum_fib += F_1
    F_0, F_1 = F_1, F_0 + F_1
print(sum_fib)